-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [issue_929_nested_borrow]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace issue_929_nested_borrow

/-- [issue_929_nested_borrow::H]
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 4:0-4:23
    Visibility: public -/
@[reducible]
def H (T : Type) := T

/-- [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]: loop body 0:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 10:8-12:9
    Visibility: public -/
@[rust_loop_body]
def H.find_max_loop.body
  {T : Type} (t : T) (iter : core.ops.range.Range Std.Usize) (max : Option T) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Option T)) (Option
    T))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done max)
  | some i =>
    let t1 ← Array.index_usize (Array.make 1#usize [ t ]) i
    ok (cont (iter1, some t1))

/-- [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]: loop 0:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 10:8-12:9
    Visibility: public -/
@[rust_loop]
def H.find_max_loop
  {T : Type} (iter : core.ops.range.Range Std.Usize) (max : Option T) (t : T) :
  Result (Option T)
  := do
  loop
    (fun (iter1, max1) => H.find_max_loop.body t iter1 max1)
    (iter, max)

/-- [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 7:4-14:5
    Visibility: public -/
@[reducible]
def H.find_max {T : Type} (self : H T) : Result (Option T) := do
  H.find_max_loop { start := 0#usize, «end» := 1#usize } none self

end issue_929_nested_borrow
