(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [issue_929_nested_borrow] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module Issue929NestedBorrow.

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 251:0-251:65
    Name pattern: [core::cmp::PartialEq]
    Visibility: public *)
Record core_cmp_PartialEq_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialEq_t {
  core_cmp_PartialEq_t_eq : Self -> Rhs -> result bool;
}.

Arguments mkcore_cmp_PartialEq_t { _ } { _ }.
Arguments core_cmp_PartialEq_t_eq { _ } { _ } _.

(** [core::cmp::Ordering]
    Source: '/rustc/library/core/src/cmp.rs', lines 396:0-396:17
    Name pattern: [core::cmp::Ordering]
    Visibility: public *)
Inductive core_cmp_Ordering_t :=
| Core_cmp_Ordering_Less : core_cmp_Ordering_t
| Core_cmp_Ordering_Equal : core_cmp_Ordering_t
| Core_cmp_Ordering_Greater : core_cmp_Ordering_t
.

(** Trait declaration: [core::cmp::PartialOrd]
    Source: '/rustc/library/core/src/cmp.rs', lines 1358:0-1359:41
    Name pattern: [core::cmp::PartialOrd]
    Visibility: public *)
Record core_cmp_PartialOrd_t (Self : Type) (Rhs : Type)
  := mkcore_cmp_PartialOrd_t {
  core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst :
    core_cmp_PartialEq_t Self Rhs;
  core_cmp_PartialOrd_t_partial_cmp : Self -> Rhs -> result (option
    core_cmp_Ordering_t);
}.

Arguments mkcore_cmp_PartialOrd_t { _ } { _ }.
Arguments core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst { _ } { _ }
  _.
Arguments core_cmp_PartialOrd_t_partial_cmp { _ } { _ } _.

(** [core::cmp::impls::{core::cmp::PartialEq<usize> for usize}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1870:16-1870:50
    Name pattern: [core::cmp::impls::{core::cmp::PartialEq<usize, usize>}::eq]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpPartialEqUsize_eq : usize -> usize -> result bool.

(** [core::cmp::impls::{core::cmp::PartialOrd<usize> for usize}::partial_cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1991:16-1991:71
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<usize, usize>}::partial_cmp]
    Visibility: public *)
Axiom Usize_Insts_CoreCmpPartialOrdUsize_partial_cmp
  : usize -> usize -> result (option core_cmp_Ordering_t)
.

(** Trait declaration: [core::iter::range::Step]
    Source: '/rustc/library/core/src/iter/range.rs', lines 32:0-32:42
    Name pattern: [core::iter::range::Step]
    Visibility: public *)
Record core_iter_range_Step_t (Self : Type) := mkcore_iter_range_Step_t {
  core_iter_range_Step_tcore_iter_range_Step_t_cloneCloneInst :
    core_clone_Clone Self;
  core_iter_range_Step_tcore_iter_range_Step_t_cmpPartialOrdInst :
    core_cmp_PartialOrd_t Self Self;
  core_iter_range_Step_t_steps_between : Self -> Self -> result (usize *
    (option usize));
  core_iter_range_Step_t_forward_checked : Self -> usize -> result (option
    Self);
  core_iter_range_Step_t_backward_checked : Self -> usize -> result (option
    Self);
}.

Arguments mkcore_iter_range_Step_t { _ }.
Arguments core_iter_range_Step_tcore_iter_range_Step_t_cloneCloneInst { _ } _.
Arguments core_iter_range_Step_tcore_iter_range_Step_t_cmpPartialOrdInst { _ }
  _.
Arguments core_iter_range_Step_t_steps_between { _ } _.
Arguments core_iter_range_Step_t_forward_checked { _ } _.
Arguments core_iter_range_Step_t_backward_checked { _ } _.

(** [core::iter::range::{core::iter::range::Step for usize}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 289:16-289:74
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::backward_checked]
    Visibility: public *)
Axiom Usize_Insts_CoreIterRangeStep_backward_checked
  : usize -> usize -> result (option usize)
.

(** [core::iter::range::{core::iter::range::Step for usize}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 281:16-281:73
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::forward_checked]
    Visibility: public *)
Axiom Usize_Insts_CoreIterRangeStep_forward_checked
  : usize -> usize -> result (option usize)
.

(** [core::iter::range::{core::iter::range::Step for usize}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 270:16-270:84
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::steps_between]
    Visibility: public *)
Axiom Usize_Insts_CoreIterRangeStep_steps_between
  : usize -> usize -> result (usize * (option usize))
.

(** Trait implementation: [core::iter::range::{core::iter::range::Step for usize}]
    Source: '/rustc/library/core/src/iter/range.rs', lines 265:12-265:37
    Name pattern: [core::iter::range::Step<usize>] *)
Definition Usize_Insts_CoreIterRangeStep : core_iter_range_Step_t usize := {|
  core_iter_range_Step_tcore_iter_range_Step_t_cloneCloneInst :=
    core_clone_CloneUsize;
  core_iter_range_Step_tcore_iter_range_Step_t_cmpPartialOrdInst :=
    core_cmp_PartialOrdUsize;
  core_iter_range_Step_t_steps_between :=
    Usize_Insts_CoreIterRangeStep_steps_between;
  core_iter_range_Step_t_forward_checked :=
    Usize_Insts_CoreIterRangeStep_forward_checked;
  core_iter_range_Step_t_backward_checked :=
    Usize_Insts_CoreIterRangeStep_backward_checked;
|}.

(** Trait declaration: [core::iter::traits::iterator::Iterator]
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 41:0-41:24
    Name pattern: [core::iter::traits::iterator::Iterator]
    Visibility: public *)
Record core_iter_traits_iterator_Iterator_t (Self : Type) (Self_Item : Type)
  := mkcore_iter_traits_iterator_Iterator_t {
  core_iter_traits_iterator_Iterator_t_next : Self -> result ((option
    Self_Item) * Self);
}.

Arguments mkcore_iter_traits_iterator_Iterator_t { _ } { _ }.
Arguments core_iter_traits_iterator_Iterator_t_next { _ } { _ } _.

(** [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::next]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 856:4-856:35
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::next]
    Visibility: public *)
Axiom core_ops_range_Range_Insts_CoreIterTraitsIteratorIterator_next :
  forall{A : Type} (stepInst : core_iter_range_Step_t A),
        core_ops_range_Range A -> result ((option A) * (core_ops_range_Range
          A))
.

(** [issue_929_nested_borrow::H]
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 4:0-4:23
    Visibility: public *)
Definition H_t (T : Type) : Type := T.

(** [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]: loop body 0:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 10:8-12:9
    Visibility: public *)
Definition h_find_max_loop_body
  {T : Type} (t : T) (iter : core_ops_range_Range usize) (max : option T) :
  result (control_flow ((core_ops_range_Range usize) * (option T)) (option T))
  :=
  p <-
    core_ops_range_Range_Insts_CoreIterTraitsIteratorIterator_next
      Usize_Insts_CoreIterRangeStep iter;
  let (o, iter1) := p in
  match o with
  | None => Ok (Done max)
  | Some i =>
    t1 <- array_index_usize (mk_array 1%usize [ t ]) i;
    Ok (Cont (iter1, Some t1))
  end
.

(** [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]: loop 0:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 10:8-12:9
    Visibility: public *)
Definition h_find_max_loop
  {T : Type} (iter : core_ops_range_Range usize) (max : option T) (t : T) :
  result (option T)
  :=
  loop
    (fun ((iter1, max1) : ((core_ops_range_Range usize) * (option T))) =>
      h_find_max_loop_body t iter1 max1)
    (iter, max)
.

(** [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 7:4-14:5
    Visibility: public *)
Definition h_find_max {T : Type} (self : H_t T) : result (option T) :=
  h_find_max_loop
    {|
      core_ops_range_Range_start := 0%usize;
      core_ops_range_Range_end_ := 1%usize
    |} None self
.

End Issue929NestedBorrow.
