(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [issue_929_nested_borrow] *)
module Issue929NestedBorrow
open Primitives

#set-options "--z3rlimit 50 --fuel 1 --ifuel 1"

(** Trait declaration: [core::cmp::PartialEq]
    Source: '/rustc/library/core/src/cmp.rs', lines 251:0-251:65
    Name pattern: [core::cmp::PartialEq]
    Visibility: public *)
noeq type core_cmp_PartialEq_t (self : Type0) (rhs : Type0) = {
  eq : self -> rhs -> result bool;
}

(** [core::cmp::Ordering]
    Source: '/rustc/library/core/src/cmp.rs', lines 396:0-396:17
    Name pattern: [core::cmp::Ordering]
    Visibility: public *)
type core_cmp_Ordering_t =
| Core_cmp_Ordering_Less : core_cmp_Ordering_t
| Core_cmp_Ordering_Equal : core_cmp_Ordering_t
| Core_cmp_Ordering_Greater : core_cmp_Ordering_t

(** Trait declaration: [core::cmp::PartialOrd]
    Source: '/rustc/library/core/src/cmp.rs', lines 1358:0-1359:41
    Name pattern: [core::cmp::PartialOrd]
    Visibility: public *)
noeq type core_cmp_PartialOrd_t (self : Type0) (rhs : Type0) = {
  partialEqInst : core_cmp_PartialEq_t self rhs;
  partial_cmp : self -> rhs -> result (option core_cmp_Ordering_t);
}

(** [core::cmp::impls::{core::cmp::PartialEq<usize> for usize}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1870:16-1870:50
    Name pattern: [core::cmp::impls::{core::cmp::PartialEq<usize, usize>}::eq]
    Visibility: public *)
assume val usize_Insts_CoreCmpPartialEqUsize_eq : usize -> usize -> result bool

(** [core::cmp::impls::{core::cmp::PartialOrd<usize> for usize}::partial_cmp]:
    Source: '/rustc/library/core/src/cmp.rs', lines 1991:16-1991:71
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<usize, usize>}::partial_cmp]
    Visibility: public *)
assume val usize_Insts_CoreCmpPartialOrdUsize_partial_cmp
  : usize -> usize -> result (option core_cmp_Ordering_t)

(** Trait declaration: [core::iter::range::Step]
    Source: '/rustc/library/core/src/iter/range.rs', lines 32:0-32:42
    Name pattern: [core::iter::range::Step]
    Visibility: public *)
noeq type core_iter_range_Step_t (self : Type0) = {
  cloneCloneInst : core_clone_Clone self;
  cmpPartialOrdInst : core_cmp_PartialOrd_t self self;
  steps_between : self -> self -> result (usize & (option usize));
  forward_checked : self -> usize -> result (option self);
  backward_checked : self -> usize -> result (option self);
}

(** [core::iter::range::{core::iter::range::Step for usize}::backward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 289:16-289:74
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::backward_checked]
    Visibility: public *)
assume val usize_Insts_CoreIterRangeStep_backward_checked
  : usize -> usize -> result (option usize)

(** [core::iter::range::{core::iter::range::Step for usize}::forward_checked]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 281:16-281:73
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::forward_checked]
    Visibility: public *)
assume val usize_Insts_CoreIterRangeStep_forward_checked
  : usize -> usize -> result (option usize)

(** [core::iter::range::{core::iter::range::Step for usize}::steps_between]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 270:16-270:84
    Name pattern: [core::iter::range::{core::iter::range::Step<usize>}::steps_between]
    Visibility: public *)
assume val usize_Insts_CoreIterRangeStep_steps_between
  : usize -> usize -> result (usize & (option usize))

(** Trait implementation: [core::iter::range::{core::iter::range::Step for usize}]
    Source: '/rustc/library/core/src/iter/range.rs', lines 265:12-265:37
    Name pattern: [core::iter::range::Step<usize>] *)
let usize_Insts_CoreIterRangeStep : core_iter_range_Step_t usize = {
  cloneCloneInst = core_clone_CloneUsize;
  cmpPartialOrdInst = core_cmp_PartialOrdUsize;
  steps_between = usize_Insts_CoreIterRangeStep_steps_between;
  forward_checked = usize_Insts_CoreIterRangeStep_forward_checked;
  backward_checked = usize_Insts_CoreIterRangeStep_backward_checked;
}

(** Trait declaration: [core::iter::traits::iterator::Iterator]
    Source: '/rustc/library/core/src/iter/traits/iterator.rs', lines 41:0-41:24
    Name pattern: [core::iter::traits::iterator::Iterator]
    Visibility: public *)
noeq type core_iter_traits_iterator_Iterator_t (self : Type0) (self_item :
  Type0) = {
  next : self -> result ((option self_item) & self);
}

(** [core::iter::range::{core::iter::traits::iterator::Iterator<A> for core::ops::range::Range<A>}::next]:
    Source: '/rustc/library/core/src/iter/range.rs', lines 856:4-856:35
    Name pattern: [core::iter::range::{core::iter::traits::iterator::Iterator<core::ops::range::Range<@A>, @A>}::next]
    Visibility: public *)
assume val core_ops_range_Range_Insts_CoreIterTraitsIteratorIterator_next
  (#a : Type0) (stepInst : core_iter_range_Step_t a) :
  core_ops_range_Range a -> result ((option a) & (core_ops_range_Range a))

(** [issue_929_nested_borrow::H]
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 4:0-4:23
    Visibility: public *)
type h_t (t : Type0) = t

(** [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]: loop body 0:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 10:8-12:9
    Visibility: public *)
let h_find_max_loop_body
  (#t : Type0) (x : t) (iter : core_ops_range_Range usize) (max : option t) :
  result (control_flow ((core_ops_range_Range usize) & (option t)) (option t))
  =
  let* (o, iter1) =
    core_ops_range_Range_Insts_CoreIterTraitsIteratorIterator_next
      usize_Insts_CoreIterRangeStep iter
  in
  begin match o with
  | None -> Ok (Done max)
  | Some i ->
    let* x1 = array_index_usize (mk_array 1 [ x ]) i in
    Ok (Cont (iter1, (Some x1)))
  end

(** [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]: loop 0:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 10:8-12:9
    Visibility: public *)
let h_find_max_loop
  (#t : Type0) (iter : core_ops_range_Range usize) (max : option t) (x : t) :
  result (option t)
  =
  loop
    (fun (iter1, max1) -> h_find_max_loop_body x iter1 max1)
    (iter, max)

(** [issue_929_nested_borrow::{issue_929_nested_borrow::H<T>}::find_max]:
    Source: 'tests/src/issue-929-nested-borrow.rs', lines 7:4-14:5
    Visibility: public *)
let h_find_max (#t : Type0) (self : h_t t) : result (option t) =
  h_find_max_loop { start = 0; end_ = 1 } None self
